<?php

/* custom routes generated by CRUD */
use App\Http\Controllers\DepartmentController;

use Illuminate\Support\Facades\Route;
Route::group(array('prefix' => 'admin/employee/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.employee.'), function () {

Route::get('employees', ['as'=> 'employees.index', 'uses' => 'Employee\EmployeeController@index']);
Route::post('employees', ['as'=> 'employees.store', 'uses' => 'Employee\EmployeeController@store']);
Route::get('employees/create', ['as'=> 'employees.create', 'uses' => 'Employee\EmployeeController@create']);
// Route::get('employees/create', ['as'=> 'employees.create', 'uses' => DepartmentController::class, 'index']);





Route::put('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::patch('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::get('employees/{id}/delete', ['as' => 'employees.delete', 'uses' => 'Employee\EmployeeController@getDelete']);
Route::get('employees/{id}/confirm-delete', ['as' => 'employees.confirm-delete', 'uses' => 'Employee\EmployeeController@getModalDelete']);
Route::get('employees/{employees}', ['as'=> 'employees.show', 'uses' => 'Employee\EmployeeController@show']);
Route::get('employees/{employees}/edit', ['as'=> 'employees.edit', 'uses' => 'Employee\EmployeeController@edit']);

});








Route::group(array('prefix' => 'admin/department/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.department.'), function () {

Route::get('departments', ['as'=> 'departments.index', 'uses' => 'Department\DepartmentController@index']);
Route::post('departments', ['as'=> 'departments.store', 'uses' => 'Department\DepartmentController@store']);
Route::get('departments/create', ['as'=> 'departments.create', 'uses' => 'Department\DepartmentController@create']);
Route::put('departments/{departments}', ['as'=> 'departments.update', 'uses' => 'Department\DepartmentController@update']);
Route::patch('departments/{departments}', ['as'=> 'departments.update', 'uses' => 'Department\DepartmentController@update']);
Route::get('departments/{id}/delete', ['as' => 'departments.delete', 'uses' => 'Department\DepartmentController@getDelete']);
Route::get('departments/{id}/confirm-delete', ['as' => 'departments.confirm-delete', 'uses' => 'Department\DepartmentController@getModalDelete']);
Route::get('departments/{departments}', ['as'=> 'departments.show', 'uses' => 'Department\DepartmentController@show']);
Route::get('departments/{departments}/edit', ['as'=> 'departments.edit', 'uses' => 'Department\DepartmentController@edit']);

});


Route::group(array('prefix' => 'admin/position/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.position.'), function () {

Route::get('positions', ['as'=> 'positions.index', 'uses' => 'Position\PositionController@index']);
Route::post('positions', ['as'=> 'positions.store', 'uses' => 'Position\PositionController@store']);
Route::get('positions/create', ['as'=> 'positions.create', 'uses' => 'Position\PositionController@create']);
Route::put('positions/{positions}', ['as'=> 'positions.update', 'uses' => 'Position\PositionController@update']);
Route::patch('positions/{positions}', ['as'=> 'positions.update', 'uses' => 'Position\PositionController@update']);
Route::get('positions/{id}/delete', ['as' => 'positions.delete', 'uses' => 'Position\PositionController@getDelete']);
Route::get('positions/{id}/confirm-delete', ['as' => 'positions.confirm-delete', 'uses' => 'Position\PositionController@getModalDelete']);
Route::get('positions/{positions}', ['as'=> 'positions.show', 'uses' => 'Position\PositionController@show']);
Route::get('positions/{positions}/edit', ['as'=> 'positions.edit', 'uses' => 'Position\PositionController@edit']);

});


Route::group(array('prefix' => 'admin/suratcuti/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.suratcuti.'), function () {

Route::get('suratcutis', ['as'=> 'suratcutis.index', 'uses' => 'Suratcuti\SuratcutiController@index']);
Route::post('suratcutis', ['as'=> 'suratcutis.store', 'uses' => 'Suratcuti\SuratcutiController@store']);
Route::get('suratcutis/create', ['as'=> 'suratcutis.create', 'uses' => 'Suratcuti\SuratcutiController@create']);
Route::put('suratcutis/{suratcutis}', ['as'=> 'suratcutis.update', 'uses' => 'Suratcuti\SuratcutiController@update']);
Route::patch('suratcutis/{suratcutis}', ['as'=> 'suratcutis.update', 'uses' => 'Suratcuti\SuratcutiController@update']);
Route::get('suratcutis/{id}/delete', ['as' => 'suratcutis.delete', 'uses' => 'Suratcuti\SuratcutiController@getDelete']);
Route::get('suratcutis/{id}/confirm-delete', ['as' => 'suratcutis.confirm-delete', 'uses' => 'Suratcuti\SuratcutiController@getModalDelete']);
Route::get('suratcutis/{suratcutis}', ['as'=> 'suratcutis.show', 'uses' => 'Suratcuti\SuratcutiController@show']);
Route::get('suratcutis/{suratcutis}/edit', ['as'=> 'suratcutis.edit', 'uses' => 'Suratcuti\SuratcutiController@edit']);

});


Route::group(array('prefix' => 'admin/absent/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.absent.'), function () {

Route::get('absents', ['as'=> 'absents.index', 'uses' => 'Absent\AbsentController@index']);
Route::post('absents', ['as'=> 'absents.store', 'uses' => 'Absent\AbsentController@store']);
Route::get('absents/create', ['as'=> 'absents.create', 'uses' => 'Absent\AbsentController@create']);
Route::put('absents/{absents}', ['as'=> 'absents.update', 'uses' => 'Absent\AbsentController@update']);
Route::patch('absents/{absents}', ['as'=> 'absents.update', 'uses' => 'Absent\AbsentController@update']);
Route::get('absents/{id}/delete', ['as' => 'absents.delete', 'uses' => 'Absent\AbsentController@getDelete']);
Route::get('absents/{id}/confirm-delete', ['as' => 'absents.confirm-delete', 'uses' => 'Absent\AbsentController@getModalDelete']);
Route::get('absents/{absents}', ['as'=> 'absents.show', 'uses' => 'Absent\AbsentController@show']);
Route::get('absents/{absents}/edit', ['as'=> 'absents.edit', 'uses' => 'Absent\AbsentController@edit']);

});


Route::group(array('prefix' => 'admin/absentdump/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.absentdump.'), function () {

Route::get('absentdumps', ['as'=> 'absentdumps.index', 'uses' => 'Absentdump\AbsentdumpController@index']);
Route::post('absentdumps', ['as'=> 'absentdumps.store', 'uses' => 'Absentdump\AbsentdumpController@store']);
Route::get('absentdumps/create', ['as'=> 'absentdumps.create', 'uses' => 'Absentdump\AbsentdumpController@create']);
Route::put('absentdumps/{absentdumps}', ['as'=> 'absentdumps.update', 'uses' => 'Absentdump\AbsentdumpController@update']);
Route::patch('absentdumps/{absentdumps}', ['as'=> 'absentdumps.update', 'uses' => 'Absentdump\AbsentdumpController@update']);
Route::get('absentdumps/{id}/delete', ['as' => 'absentdumps.delete', 'uses' => 'Absentdump\AbsentdumpController@getDelete']);
Route::get('absentdumps/{id}/confirm-delete', ['as' => 'absentdumps.confirm-delete', 'uses' => 'Absentdump\AbsentdumpController@getModalDelete']);
Route::get('absentdumps/{absentdumps}', ['as'=> 'absentdumps.show', 'uses' => 'Absentdump\AbsentdumpController@show']);
Route::get('absentdumps/{absentdumps}/edit', ['as'=> 'absentdumps.edit', 'uses' => 'Absentdump\AbsentdumpController@edit']);

});


Route::group(array('prefix' => 'admin/period/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.period.'), function () {

Route::get('periods', ['as'=> 'periods.index', 'uses' => 'Period\PeriodController@index']);
Route::post('periods', ['as'=> 'periods.store', 'uses' => 'Period\PeriodController@store']);
Route::get('periods/create', ['as'=> 'periods.create', 'uses' => 'Period\PeriodController@create']);
Route::put('periods/{periods}', ['as'=> 'periods.update', 'uses' => 'Period\PeriodController@update']);
Route::patch('periods/{periods}', ['as'=> 'periods.update', 'uses' => 'Period\PeriodController@update']);
Route::get('periods/{id}/delete', ['as' => 'periods.delete', 'uses' => 'Period\PeriodController@getDelete']);
Route::get('periods/{id}/confirm-delete', ['as' => 'periods.confirm-delete', 'uses' => 'Period\PeriodController@getModalDelete']);
Route::get('periods/{periods}', ['as'=> 'periods.show', 'uses' => 'Period\PeriodController@show']);
Route::get('periods/{periods}/edit', ['as'=> 'periods.edit', 'uses' => 'Period\PeriodController@edit']);

});


Route::group(array('prefix' => 'admin/aset/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.aset.'), function () {

Route::get('asets', ['as'=> 'asets.index', 'uses' => 'Aset\AsetController@index']);
Route::post('asets', ['as'=> 'asets.store', 'uses' => 'Aset\AsetController@store']);
Route::get('asets/create', ['as'=> 'asets.create', 'uses' => 'Aset\AsetController@create']);
Route::put('asets/{asets}', ['as'=> 'asets.update', 'uses' => 'Aset\AsetController@update']);
Route::patch('asets/{asets}', ['as'=> 'asets.update', 'uses' => 'Aset\AsetController@update']);
Route::get('asets/{id}/delete', ['as' => 'asets.delete', 'uses' => 'Aset\AsetController@getDelete']);
Route::get('asets/{id}/confirm-delete', ['as' => 'asets.confirm-delete', 'uses' => 'Aset\AsetController@getModalDelete']);
Route::get('asets/{asets}', ['as'=> 'asets.show', 'uses' => 'Aset\AsetController@show']);
Route::get('asets/{asets}/edit', ['as'=> 'asets.edit', 'uses' => 'Aset\AsetController@edit']);

});

Route::get('admin/asettaking/asettakings', ['as'=> 'admin.asettaking.asettakings.index', 'uses' => 'Admin\AsetTaking\AsetTakingController@index']);
Route::get('admin/asettaking/asettakings/data', 'Admin\AsetTaking\AsetTakingController@data')->name('admin.asettaking.asettakings.data');
Route::get('admin/asettaking/asettakings/{id}/delete', 'Admin\AsetTaking\AsetTakingController@destroy')->name('admin.asettaking.asettakings.delete');

